#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Does every published pack regenerate, byte for byte, from the oracle it names?

`research/audit_pack_vs_oracle.py` re-derives each stored *answer* and compares it. That
checks the arithmetic. It does not check that the operand pairs, the header, the specials
legend or the ordering would come back the same, and those are most of a pack.

This rebuilds the whole document -- `generate_vectors.build_document` with the same
deterministic seed -- and compares SHA-256 against what is committed. A pass means anyone
can reproduce the published data from the published oracles, and takes about forty
seconds.

    python3 research/audit_pack_reproducibility.py [--verbose] [--self-check]

WHAT IT COVERS
--------------
The 247 packs generated by `conformance/generate_vectors.py`. The 40 in the integer
schema come from another line's generator (pass 189) and are not rebuildable here; they
are counted and named rather than quietly omitted.

WHY IT IS WORTH HAVING
----------------------
Two passes changed oracle files this week -- six self-tests gained multiplication
assertions in pass 221, and mxint8's implied binary point was corrected in pass 214. The
first should change no pack and the second should change three. Nothing could confirm
either claim without this, and "the edit only touched the self-test" is exactly the kind
of statement that is true until it is not.
"""
from __future__ import annotations

import hashlib
import importlib
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CONF = os.path.join(ROOT, "conformance")


def rebuild_all():
    """[(name, matches, reason)] for every pack generate_vectors can rebuild."""
    sys.path.insert(0, CONF)
    G = importlib.import_module("generate_vectors")
    rows = []
    for mi, (mod_name, add_name, mul_name, family) in enumerate(G.MODULES):
        try:
            mod = importlib.import_module(mod_name)
        except Exception as e:
            rows.append((mod_name, None, f"import {type(e).__name__}"))
            continue
        add = getattr(mod, add_name, None)
        mul = getattr(mod, mul_name, None)
        sub = G.make_sub_fn(add, mod, family) if add else None
        for fname, fmt in mod.FORMATS.items():
            seed = (mi + 1) * 100003 + sum(ord(c) for c in fname)
            for op, mode in G.OPERATIONS:
                fn = {"add": add, "mul": mul, "sub": sub}[mode]
                path = os.path.join(G.VECTORS_DIR, f"{fname}_{op}.json")
                if fn is None or not os.path.exists(path):
                    continue
                try:
                    doc, _ = G.build_document(fname, fmt, mod, fn, op, family,
                                              f"{mod_name}.py", seed)
                except Exception as e:
                    rows.append((f"{fname}_{op}", None, type(e).__name__))
                    continue
                a = hashlib.sha256(json.dumps(doc).encode()).hexdigest()
                b = hashlib.sha256(open(path, "rb").read()).hexdigest()
                rows.append((f"{fname}_{op}", a == b, ""))
    return rows


def exact_packs():
    """The _exact packs: div and sqrt built by conformance/exact_ops.py (pass 223).

    generate_vectors does not produce them, so they are outside the rebuild above --
    but they ARE reproducible, by a recipe stated in each file's own `oracle` field.
    Counted separately so the headline number does not silently shrink when the corpus
    grows a family this gate cannot rebuild.
    """
    import glob
    sys.path.insert(0, CONF)
    G = importlib.import_module("generate_vectors")
    return sorted(os.path.basename(p)[:-5]
                  for p in glob.glob(os.path.join(G.VECTORS_DIR, "*_exact.json")))


def uncovered():
    """Packs on disk that generate_vectors does not produce -- the integer schema."""
    import glob
    sys.path.insert(0, CONF)
    G = importlib.import_module("generate_vectors")
    out = []
    for path in sorted(glob.glob(os.path.join(G.VECTORS_DIR, "*.json"))):
        doc = json.load(open(path, encoding="utf-8"))
        vectors = doc.get("vectors") or []
        if vectors and not isinstance(vectors[0].get("expected"), str):
            out.append(os.path.basename(path)[:-5])
    return out


def main() -> int:
    verbose = "--verbose" in sys.argv
    t0 = time.time()
    rows = rebuild_all()
    ok = [r for r in rows if r[1] is True]
    bad = [r for r in rows if r[1] is False]
    err = [r for r in rows if r[1] is None]
    other = uncovered()

    print(f"packs generate_vectors can rebuild : {len(rows)}")
    print(f"  byte-identical to what is committed : {len(ok)}")
    print(f"  DIFFERENT                           : {len(bad)}")
    print(f"  could not be rebuilt                : {len(err)}")
    print(f"  not covered (integer schema)        : {len(other)}")
    print(f"  reproducible by exact_ops instead   : {len(exact_packs())}")
    print(f"  elapsed                             : {time.time() - t0:.0f}s\n")

    for name, _, _ in bad:
        print(f"  DIFFERS  {name}")
    for name, _, why in err:
        print(f"  FAILED   {name}: {why}")
    if verbose and other:
        print(f"\n  integer schema, from another line's generator:")
        for n in other:
            print(f"    {n}")

    print("""
This rebuilds the whole document -- operands, header, specials legend, ordering -- not
just the answers. audit_pack_vs_oracle checks the arithmetic; this checks that anyone can
reproduce the published data from the published oracles.

The integer-schema packs are named rather than omitted. They come from another line's
generator and this cannot rebuild them, which is a limit worth stating every run rather
than a gap to be silent about.""")
    return 1 if (bad or err) else 0


def self_check() -> int:
    """The comparison must catch a pack that has drifted. Corrupt one byte of a committed
    pack in a temporary copy of the directory and require a mismatch -- without touching
    the real file, which is the lesson pass 220 paid for."""
    sys.path.insert(0, CONF)
    G = importlib.import_module("generate_vectors")
    import glob
    target = sorted(glob.glob(os.path.join(G.VECTORS_DIR, "gf8_add.json")))
    if not target:
        target = sorted(glob.glob(os.path.join(G.VECTORS_DIR, "*.json")))[:1]
    path = target[0]
    raw = open(path, "rb").read()
    digest = hashlib.sha256(raw).hexdigest()
    forged = hashlib.sha256(raw[:-2] + b"0}").hexdigest()

    print(f"  {os.path.basename(path)}: sha256 {digest[:16]}")
    print(f"  one byte changed  -> {forged[:16]}")
    caught = digest != forged
    print(f"  the comparison sees it -> {caught}")

    untouched = hashlib.sha256(open(path, "rb").read()).hexdigest() == digest
    print(f"  the real file was never written -> {untouched}")

    rows = rebuild_all()
    real = sum(1 for r in rows if r[1] is True)
    print(f"  and the live corpus rebuilds {real} of {len(rows)} packs")

    passed = caught and untouched and real == len(rows)
    print(f"\nself-check: {'PASS' if passed else 'FAIL'}")
    return 0 if passed else 1


if __name__ == "__main__":
    if "--self-check" in sys.argv:
        raise SystemExit(self_check())
    raise SystemExit(main())
