#!/usr/bin/env python3
"""Does anything that produces the papers' evidence hardcode a path from one machine?

conformance/gf48_bitexact_oracle.py wrote its output to

    /home/user/workspace/trinity-fpga/conformance/gf48_vectors.hex

which exists on exactly one machine. Everywhere else the script printed

    WITNESS CROSS-CHECK (A exact-Fraction vs B integer-construct): 9616/9616 agree

and then died with FileNotFoundError. The good news arrived, the failure followed,
and the committed conformance/gf48_vectors.hex could not be regenerated by the
script that claims to produce it.

The vectors were fine -- once the path was made relative, the regenerated file was
byte-identical to the committed one, SHA-256 ab828d62d7ce2e9c. That is the point:
the artifact was right and unreproducible at the same time, and only one of those
two things is visible from reading the artifact.

SCOPE, DELIBERATELY NARROW
--------------------------
53 files across this repo contain an absolute /Users or /home path. Most are
legacy: a Kaggle uploader, a Solidity build cache, deploy scripts for a service
that no longer runs. Failing a gate on those would produce a number nobody acts
on, which is the failure mode pass 278 had to split out of audit_yosys_reads.

So this looks only where a hardcoded path would corrupt evidence:

    conformance/     oracles and packs
    fpga/witness/    the decode and arithmetic witnesses
    research/        the audits and witnesses themselves

and only at files that are RUN. Three kinds of text get confused here and only one
of them is a defect:

    code      an expression that opens or imports the path. This breaks.
    prose     a docstring or comment mentioning it. Misleads a reader; runs fine.
    record    a .t27 spec or .json pack that WRITES DOWN where some other
              machine's files were. specs/numeric/script_tree_sweep.t27 holds
              eleven such paths because that is its entire subject.

Only `code` fails this gate. The first version line-scanned every non-Python file,
counted records as code, and reported 15 defects of which 15 were records -- a
number that is mostly false, in the gate written to stop numbers being mostly
false, two passes after that same failure was split out of audit_yosys_reads.

Usage:  python3 research/audit_absolute_paths.py [--verbose]

Exits non-zero if executable code in those directories hardcodes such a path.
"""
import io
import os
import re
import sys
import tokenize

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DIRS = ["conformance", os.path.join("fpga", "witness"), "research"]
PAT = re.compile(r"/(?:Users|home)/[A-Za-z0-9._-]+/[^\s\"'`,;:)\]}]*")

# This file quotes the very path it exists to ban, in its own docstring. So does
# any honest write-up of the finding. Comments and strings are separated from code
# by the tokenizer rather than by guessing, so the explanation can stay.
SELF = os.path.basename(__file__)


RECORD_EXT = {".t27", ".json"}      # data this campaign WRITES, not code it runs


def scan(path):
    """(code_hits, prose_hits). Uses the tokenizer, so a path in a docstring is
    never mistaken for one in an expression, and vice versa.

    A .t27 spec or a .json pack is a RECORD. specs/numeric/script_tree_sweep.t27
    contains eleven /home/user/workspace paths because its entire subject is where
    some other machine's scripts lived -- writing them down is the finding, not a
    defect. The first version of this gate line-scanned every non-Python file and
    called all of it executable, and reported 15 defects of which 15 were records.
    A number that is mostly false, in the gate written to stop numbers being
    mostly false, two passes after that failure was split out of
    audit_yosys_reads. Caught before it shipped, but only just."""
    code, prose = [], []
    ext = os.path.splitext(path)[1]
    if ext in RECORD_EXT:
        return [], []
    try:
        with open(path, "rb") as fh:
            toks = list(tokenize.tokenize(fh.readline))
    except Exception:
        # Verilog and anything else that is executed but is not Python: line-scan
        # and call it code. $readmemb "path" is a real dependency on a filesystem.
        try:
            for i, ln in enumerate(io.open(path, encoding="utf-8",
                                           errors="replace"), 1):
                for m in PAT.finditer(ln):
                    code.append((i, m.group(0)))
        except Exception:
            pass
        return code, prose
    for tok in toks:
        if tok.type == tokenize.COMMENT:
            bucket = prose
        elif tok.type == tokenize.STRING:
            # A string is code if it is used as a value. A docstring is a bare
            # expression statement -- indistinguishable here without full parsing,
            # so the conservative call: a triple-quoted string at column 0 is
            # prose, anything else is code.
            bucket = prose if (tok.start[1] == 0 and tok.string[:3] in ('"""', "'''")) else code
        else:
            continue
        for m in PAT.finditer(tok.string):
            bucket.append((tok.start[0], m.group(0)))
    return code, prose


def main():
    verbose = "--verbose" in sys.argv
    code_hits, prose_hits, scanned = [], [], 0
    for d in DIRS:
        base = os.path.join(ROOT, d)
        for dp, dn, fn in os.walk(base):
            dn[:] = [x for x in dn if x not in {"__pycache__", "vectors", ".gate_cache"}]
            for f in sorted(fn):
                if not f.endswith((".py", ".t27", ".v", ".json")):
                    continue
                if f == SELF:
                    continue
                p = os.path.join(dp, f)
                if os.path.getsize(p) > 2_000_000:
                    continue
                scanned += 1
                c, pr = scan(p)
                rel = os.path.relpath(p, ROOT)
                code_hits += [(rel, n, s) for n, s in c]
                prose_hits += [(rel, n, s) for n, s in pr]

    print("files scanned in %s : %d" % (", ".join(DIRS), scanned))
    print()
    print("EXECUTABLE references to an absolute /Users or /home path : %d"
          % len(code_hits))
    for rel, n, s in code_hits:
        print("    %s:%d  %s" % (rel, n, s[:80]))
    print("the same path in a comment or docstring (misleading, not broken) : %d"
          % len(prose_hits))
    if verbose:
        for rel, n, s in prose_hits:
            print("    %s:%d  %s" % (rel, n, s[:80]))
    elif prose_hits:
        for rel, n, s in prose_hits[:3]:
            print("    %s:%d  %s" % (rel, n, s[:80]))
        if len(prose_hits) > 3:
            print("    ... and %d more (--verbose)" % (len(prose_hits) - 3))
    print()
    if not code_hits:
        print("nothing that produces evidence depends on one machine's filesystem.")
    return 1 if code_hits else 0


if __name__ == "__main__":
    sys.exit(main())
