#!/usr/bin/env python3
"""Emit ready-to-paste LaTeX for every reference in the defect list.

Reads research/bibliography_defects.py -- the same list BIBLIOGRAPHY_FIXES.md is
built from. They were maintained separately until pass 80 and had drifted to 11
entries against 20, so anyone pasting from the .tex would have skipped nine
defects including two misattributions.

Titles and full author lists are fetched from the arXiv API at generation time, not
transcribed. The audit scripts truncate author lists to four for display; ProofWright
has five authors and M2XFP eleven, and a bibliography being corrected for wrong
author lists should not ship short ones.

    python3 research/build_corrected_bibitems.py > research/CORRECTED_BIBITEMS.tex
"""
from __future__ import annotations

import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bibliography_defects import DEFECTS, arxiv_ids            # noqa: E402


def fetch(ids):
    url = ("https://export.arxiv.org/api/query?max_results=100&id_list="
           + ",".join(sorted(set(ids))))
    out = subprocess.check_output(["curl", "-sS", "--max-time", "90", url],
                                  text=True)
    found = {}
    for chunk in out.split("<entry>")[1:]:
        m = re.search(r"arxiv\.org/abs/([0-9]{4}\.[0-9]{4,5})", chunk)
        if not m:
            continue
        t = re.search(r"<title>(.*?)</title>", chunk, re.S)
        names = re.findall(r"<name>(.*?)</name>", chunk, re.S)
        pub = re.search(r"<published>(\d{4})", chunk)
        found[m.group(1)] = (" ".join(t.group(1).split()) if t else "",
                             [n.strip() for n in names],
                             pub.group(1) if pub else "")
    return found


def latex_authors(names):
    out = []
    for n in names:
        parts = n.split()
        if len(parts) < 2:
            out.append(n)
            continue
        out.append(" ".join(p[0] + "." for p in parts[:-1]) + " " + parts[-1])
    if len(out) == 1:
        return out[0]
    if len(out) == 2:
        return " and ".join(out)
    return ", ".join(out[:-1]) + ", and " + out[-1]


def main() -> int:
    meta = fetch(arxiv_ids())

    print("% Corrected bibitems for BOTH papers.")
    print("% Generated by research/build_corrected_bibitems.py from")
    print("% research/bibliography_defects.py -- the same list that produces")
    print("% BIBLIOGRAPHY_FIXES.md, so the two cannot disagree.")
    print("%")
    print("% Titles and author lists are fetched from the arXiv API at generation")
    print("% time. Verify against the rendered PDF before submitting.\n")

    for paper in ("A", "B"):
        rows = [d for d in DEFECTS if d["paper"] == paper]
        print(f"\n% ==========================================================")
        print(f"% Paper {paper} — {len(rows)} entries")
        print(f"% ==========================================================\n")
        for d in rows:
            kind, ident = d["ident"]
            print(f"% {d['ref']}  — {d['defect']}")
            if d.get("note"):
                flat = re.sub(r"[*`]", "", d["note"])
                for line in re.findall(r".{1,72}(?:\s|$)", flat):
                    print(f"%   {line.strip()}")
            if d.get("latex"):
                print(d["latex"] + "\n")
                continue
            if kind != "arxiv":
                print("% (no replacement generated — see the note above)\n")
                continue
            got = meta.get(ident)
            if not got:
                print(f"% arXiv:{ident} did not resolve — check by hand\n")
                continue
            title, names, year = got
            print(f"\\bibitem{{{d['key']}}} {latex_authors(names)}, ``{title},''")
            print(f"  \\texttt{{arXiv:{ident}}}, {year}.\n")

    n = len(DEFECTS)
    print(f"% {n} entries total. If this number disagrees with")
    print("% BIBLIOGRAPHY_FIXES.md, one of the generators was not re-run.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
