#!/usr/bin/env python3
"""Build one table of every bibliography defect in both papers.

The findings are currently spread across SUBMISSION_CHECKLIST.md, three .t27 specs
and CORRECTED_BIBITEMS.tex. An author fixing a bibliography needs one list: which
entry, what is wrong with it, what it should say.

Everything is re-resolved from the live arXiv API at generation time rather than
copied from an earlier report, so the table cannot drift from the evidence. Entries
that carry no arXiv id are stated with their source named.

    python3 research/build_bibliography_table.py > research/BIBLIOGRAPHY_FIXES.md
"""
from __future__ import annotations

import html
import re
import subprocess
import sys

PAPERS = {"A": "2606.05017v3", "B": "2606.09686v2"}

# ref -> (paper, arxiv id, defect class)
ARXIV_DEFECTS = [
    ("B", "[1]",  "2606.05017", "wrong title — the companion paper"),
    ("B", "[2]",  "2412.20273", "wrong title — different work"),
    ("B", "[3]",  "2511.12294", "wrong title AND wrong subject"),
    ("B", "[4]",  "2602.15965", "paraphrased title"),
    ("B", "[8]",  "2601.19213", "wrong title — subtitle invented"),
    ("B", "[10]", "2504.07835", "paraphrased title"),
    ("B", "[13]", "2412.20268", "wrong title — different work"),
    ("B", "[19]", "2606.04028", "no title given at all"),
    ("B", "[20]", "2601.19026", "no title given at all"),
    ("A", "[7]",  "2404.18603", "shortened title"),
    ("A", "[8]",  "2412.20273", "paraphrased — scope changed"),
    ("A", "[9]",  "2408.10594", "paraphrased — invents 'VHDL'"),
    ("A", "[10]", "2412.20268", "paraphrased title"),
    ("A", "[22]", "2402.17764", "shortened title"),
    ("A", "[26]", "2511.01921", "paraphrased — domain changed"),
]

OTHER_DEFECTS = [
    ("A", "[11]", "DOI 10.1109/ARITH64983.2025.00019 resolves to *Evaluation of "
                  "Bfloat16, Posit, and Takum Arithmetics in Sparse Linear "
                  "Solvers* (Hunhold and Quinlan) — **the same work [10] already "
                  "cites**. Wrong title, wrong authors, and a duplicate.",
     "Delete as a duplicate of [10]. If the ARITH 2025 hardware-evaluation paper "
     "was intended, it needs its own DOI — this one is not it."),
    ("B", "[12]", "credits *C.* Hunhold for libtakum.",
     "The author is **Laslo** Hunhold — confirmed from the arXiv record for "
     "2404.18603."),
    ("B", "[18]", "cites *IEEE SA P3109 Interim Report **v3.2.0***.",
     "That document carries no version number anywhere in its text. Cite it by "
     "retrieval date."),
]


def fetch(ids):
    url = ("https://export.arxiv.org/api/query?max_results=100&id_list="
           + ",".join(sorted(set(ids))))
    out = subprocess.check_output(["curl", "-sS", "--max-time", "90", url],
                                  text=True)
    found = {}
    for chunk in out.split("<entry>")[1:]:
        m = re.search(r"arxiv\.org/abs/([0-9]{4}\.[0-9]{4,5})", chunk)
        if not m:
            continue
        t = re.search(r"<title>(.*?)</title>", chunk, re.S)
        names = re.findall(r"<name>(.*?)</name>", chunk, re.S)
        found[m.group(1)] = (" ".join(t.group(1).split()) if t else "",
                             [n.strip() for n in names])
    return found


def cited_titles(paper_id):
    """What each entry currently claims, read from the published HTML."""
    url = f"https://arxiv.org/html/{paper_id}"
    raw = subprocess.check_output(["curl", "-sSL", "--max-time", "90", url],
                                  text=True, stderr=subprocess.DEVNULL)
    out = {}
    for i, item in enumerate(re.findall(
            r'<li[^>]*class="[^"]*ltx_bibitem[^"]*"[^>]*>(.*?)</li>',
            raw, re.S | re.I), 1):
        txt = " ".join(html.unescape(re.sub(r"<[^>]+>", " ", item)).split())
        q = re.search(r"[“\"']([^”\"']{6,200})[”\"']", txt)
        out[f"[{i}]"] = q.group(1).strip().rstrip(",") if q else "(no title)"
    return out


def main() -> int:
    meta = fetch([a for _, _, a, _ in ARXIV_DEFECTS])
    cited = {p: cited_titles(pid) for p, pid in PAPERS.items()}

    print("# Bibliography fixes — every defect in both papers, in one table\n")
    print("> Generated by `research/build_bibliography_table.py`, which re-resolves")
    print("> every identifier against the live arXiv API at generation time. Nothing")
    print("> here is transcribed from an earlier report.\n>")
    print("> Ready-to-paste LaTeX for these entries is in `CORRECTED_BIBITEMS.tex`.\n")

    for paper, pid in PAPERS.items():
        rows = [r for r in ARXIV_DEFECTS if r[0] == paper]
        others = [r for r in OTHER_DEFECTS if r[0] == paper]
        print(f"\n## Paper {paper} — arXiv:{pid}\n")
        print(f"**{len(rows) + len(others)} entries need attention.**\n")
        print("| ref | currently says | actually is | defect |")
        print("|---|---|---|---|")
        for _, ref, aid, defect in rows:
            real_title, names = meta.get(aid, ("(unresolved)", []))
            claim = cited[paper].get(ref, "?")
            who = names[0].split()[-1] if names else ""
            extra = f" *({who}{' et al.' if len(names) > 1 else ''})*" if who else ""
            print(f"| **{ref}** | {claim[:78]} | {real_title[:82]}{extra} | {defect} |")
        print()
        for _, ref, what, fix in others:
            print(f"- **{ref}** — {what}  \n  → {fix}\n")

    print("""
---

### How this list was produced, and what it does not cover

Every arXiv identifier in both bibliographies was resolved and its title compared
against what the entry claims. That catches the class that matters: a citation that
*looks* right and points somewhere else.

It does **not** cover entries with no machine-resolvable identifier. In Paper A those
are `[1]` (1957 journal article), `[6]` (HAL), `[27]` (working draft) and `[30]`
(forum post); `[23]` and `[33]` carry ISBNs and both resolve correctly. In Paper B
they are `[11]`, `[15]`, `[16]`, `[17]`, whose URLs were checked and resolve.

One duplicate was found only by resolving two different identifier types and
noticing they met — Paper A's `[10]` and `[11]`. Identifier matching alone would not
have found it, so there may be others of that shape.
""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
