#!/usr/bin/env python3
"""Build one table of every bibliography defect in both papers.

The findings are currently spread across SUBMISSION_CHECKLIST.md, three .t27 specs
and CORRECTED_BIBITEMS.tex. An author fixing a bibliography needs one list: which
entry, what is wrong with it, what it should say.

Everything is re-resolved from the live arXiv API at generation time rather than
copied from an earlier report, so the table cannot drift from the evidence. Entries
that carry no arXiv id are stated with their source named.

    python3 research/build_bibliography_table.py > research/BIBLIOGRAPHY_FIXES.md
"""
from __future__ import annotations

import html
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from bibliography_defects import DEFECTS                       # noqa: E402

PAPERS = {"A": "2606.05017v3", "B": "2606.09686v2"}

ARXIV_DEFECTS = [(d["paper"], d["ref"], d["ident"][1], d["defect"])
                 for d in DEFECTS if d["ident"][0] == "arxiv"]
OTHER_DEFECTS = [(d["paper"], d["ref"], d.get("note", d["defect"]), d.get("fix", ""))
                 for d in DEFECTS if d["ident"][0] != "arxiv"]


def fetch(ids):
    url = ("https://export.arxiv.org/api/query?max_results=100&id_list="
           + ",".join(sorted(set(ids))))
    out = subprocess.check_output(["curl", "-sS", "--max-time", "90", url],
                                  text=True)
    found = {}
    for chunk in out.split("<entry>")[1:]:
        m = re.search(r"arxiv\.org/abs/([0-9]{4}\.[0-9]{4,5})", chunk)
        if not m:
            continue
        t = re.search(r"<title>(.*?)</title>", chunk, re.S)
        names = re.findall(r"<name>(.*?)</name>", chunk, re.S)
        found[m.group(1)] = (" ".join(t.group(1).split()) if t else "",
                             [n.strip() for n in names])
    return found


def cited_titles(paper_id):
    """What each entry currently claims, read from the published HTML."""
    url = f"https://arxiv.org/html/{paper_id}"
    raw = subprocess.check_output(["curl", "-sSL", "--max-time", "90", url],
                                  text=True, stderr=subprocess.DEVNULL)
    out = {}
    for i, item in enumerate(re.findall(
            r'<li[^>]*class="[^"]*ltx_bibitem[^"]*"[^>]*>(.*?)</li>',
            raw, re.S | re.I), 1):
        txt = " ".join(html.unescape(re.sub(r"<[^>]+>", " ", item)).split())
        q = re.search(r"[“\"']([^”\"']{6,200})[”\"']", txt)
        out[f"[{i}]"] = q.group(1).strip().rstrip(",") if q else "(no title)"
    return out


def main() -> int:
    meta = fetch([a for _, _, a, _ in ARXIV_DEFECTS])
    cited = {p: cited_titles(pid) for p, pid in PAPERS.items()}

    print("# Bibliography fixes — every defect in both papers, in one table\n")
    print("> Generated by `research/build_bibliography_table.py`, which re-resolves")
    print("> every identifier against the live arXiv API at generation time. Nothing")
    print("> here is transcribed from an earlier report.\n>")
    print("> Ready-to-paste LaTeX for these entries is in `CORRECTED_BIBITEMS.tex`.\n")

    for paper, pid in PAPERS.items():
        rows = [r for r in ARXIV_DEFECTS if r[0] == paper]
        others = [r for r in OTHER_DEFECTS if r[0] == paper]
        print(f"\n## Paper {paper} — arXiv:{pid}\n")
        print(f"**{len(rows) + len(others)} entries need attention.**\n")
        print("| ref | currently says | actually is | defect |")
        print("|---|---|---|---|")
        for _, ref, aid, defect in rows:
            real_title, names = meta.get(aid, ("(unresolved)", []))
            claim = cited[paper].get(ref, "?")
            who = names[0].split()[-1] if names else ""
            extra = f" *({who}{' et al.' if len(names) > 1 else ''})*" if who else ""
            print(f"| **{ref}** | {claim[:78]} | {real_title[:82]}{extra} | {defect} |")
        print()
        for _, ref, what, fix in others:
            print(f"- **{ref}** — {what}  \n  → {fix}\n")

    print("""
---

### How this list was produced, and what it does not cover

Every arXiv identifier in both bibliographies was resolved and its title compared
against what the entry claims. That catches the class that matters: a citation that
*looks* right and points somewhere else.

Entries without an arXiv id were pursued through whatever identifier they carry:

- **ISBN** — Paper A `[23]` and `[33]` resolve via OpenLibrary and both agree with
  what is cited. (One lead, not a defect: `[23]` is dated 2015 and OpenLibrary
  records 2017; editions exist under both.)
- **HAL** — Paper A `[6]` resolves, and **disagrees** — it is in the table above.
- **A bare URL** — Paper B `[11]`'s own link was fetched and read; it **disagrees**,
  and is in the table above. `[15]`, `[16]` and `[17]` are a standard, a
  specification and a library repository, whose URLs resolve.

**Still not covered:** Paper A `[1]` (a 1957 journal article with no identifier),
`[27]` (an unversioned working draft) and `[30]` (a forum post). Those three cannot
be checked mechanically.

**Duplicates** were searched for twice: by identifier, which found none, and by
resolving every identifier to a canonical title and grouping — which recovered Paper
A's `[10]`/`[11]` pair, where one entry carries an arXiv id and the other a DOI for
the same work. That second method is what the first misses by construction; it found
no others in either paper among the 26 of 33 and 12 of 20 entries it could resolve.
""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
