// GENERATED by tools/gen_setkey_golden.py — do not hand-edit.
// Values come from the Python golden implementation, not from the RTL.
localparam [63:0] GOLD_SETKEY_ACK = 64'hdbc8fbb1739713b5;
localparam [63:0] GOLD_MAC_A = 64'h5dac40749c246040;
localparam [63:0] GOLD_MAC_B = 64'hd9173efbc78c1fc6;
localparam [63:0] GOLD_MAC_C = 64'h8b8f99f138f8dfe5;
