#!/usr/bin/env python3
"""Emit the golden tags formal/trinet_setkey_tb.v checks against.

They come from conformance/trinet_mac32_conformance_ax7203.py — the independent
Python implementation — and never from the RTL. A testbench whose expected
values were read off the design under test only proves the design is
self-consistent, which it always is.

Usage: python3 tools/gen_setkey_golden.py > formal/trinet_setkey_golden.vh

Author: Dmitrii Vasilev (@gHashTag)
"""

import importlib.util
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
spec = importlib.util.spec_from_file_location(
    "conf", ROOT / "conformance" / "trinet_mac32_conformance_ax7203.py")
conf = importlib.util.module_from_spec(spec)
_argv, sys.argv = sys.argv, ["gen"]
try:
    spec.loader.exec_module(conf)
except SystemExit:
    pass
sys.argv = _argv

OP_MAC32, OP_SETKEY = 0x01, 0x02
NODE = 0x5452494E
KEY1 = bytes(range(16))            # what the testbench installs

def tag(op, nonce, w, x, y, key):
    return conf.golden_receipt_tag_keyed(
        op, nonce.to_bytes(4, "big"), w.to_bytes(8, "big"),
        x.to_bytes(8, "big"), y, NODE, key)

# The set-key acknowledgement: operands are the key bytes, y is forced to zero,
# and it is signed with the key just accepted — that is what makes the ack
# evidence of acceptance rather than an echo.
ack = tag(OP_SETKEY, 2, int.from_bytes(KEY1[:8], "big"),
          int.from_bytes(KEY1[8:], "big"), 0, KEY1)

mac_a = tag(OP_MAC32, 3, 0x5555555555555555, 0x5555555555555555, 0x20, KEY1)
mac_b = tag(OP_MAC32, 4, 0x5555555555555555, 0xaaaaaaaaaaaaaaaa, 0xe0, KEY1)
mac_c = tag(OP_MAC32, 6, 0x5555555555555555, 0x5555555555555555, 0x20, KEY1)

print("// GENERATED by tools/gen_setkey_golden.py — do not hand-edit.")
print("// Values come from the Python golden implementation, not from the RTL.")
for name, v in [("GOLD_SETKEY_ACK", ack), ("GOLD_MAC_A", mac_a),
                ("GOLD_MAC_B", mac_b), ("GOLD_MAC_C", mac_c)]:
    print(f"localparam [63:0] {name} = 64'h{v:016x};")
