name: AX7203 Compute uint32-add
on:
  push:
    paths:
      - 'fpga/openxc7-synth/corona_compute_uint32_add_ax7203.v'
      - 'fpga/openxc7-synth/gf_adder_param.v'
      - 'fpga/openxc7-synth/gf_mul_param.v'
  workflow_dispatch:

jobs:
  synth:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Yosys synthesis
        uses: docker://regymm/openxc7:latest
        with:
          args: bash -c "cd fpga/openxc7-synth && yosys -p 'read_verilog gf_adder_param.v gf_mul_param.v corona_compute_uint32_add_ax7203.v; synth_xilinx -abc9 -nocarry -arch xc7; write_json corona_compute_uint32_add_ax7203.json'"
